### PR TITLE
TFAC-1018 GroupImpactSidebar pt.1 (Excluding Animations)

### PR DESCRIPTION
**Pull request by jedtan**
First pass on the GroupImpactSidebar. I'll include animations in a later PR. Also would like your feedback on what the "collapse sidebar" button should look like (hover, how big the button should be, etc).

### CODE REVIEW

**Review by kmjennison — COMMENTED** [review]
Nice work on this! Feedback:

* Does using the MUI drawer component cover what you need with animation? https://mui.com/material-ui/react-drawer/#main-content
* Cut the "participants". Sorry, that was updated in the Figma [prototype page](https://www.figma.com/file/fKLCz2GfPG5f6HhEj9BlWD/Group-impact?node-id=152%3A10857&t=tkDjBerjKgcP7t9j-0) but not the prior static page.
* Buttons:
  * Drawer close button feels a little asymmetric. Maybe it should be a circle here?
  * "About the Cause" button definitely needs padding. I wonder if we overstepped on the button border-radius customization that forces 50% of height, because I think this kind of square-ish button breaks it. Thoughts?
* Vertical sidebar:
  * The entire sidebar should have button behavior (`cursor: pointer`)
  * See behavior in [prototype](https://www.figma.com/proto/fKLCz2GfPG5f6HhEj9BlWD/Group-impact?node-id=152%3A11013&scaling=min-zoom&page-id=152%3A10857&starting-point-node-id=152%3A11013)
  * This might not be in scope of feedback you want now, but just flagging it.
* Storybook/Chromatic:
  * Let's have a story of the open sidebar for UI testing
  * Might be helpful in evaluating animation behavior to have sidebar/progress vertically fill the story height and set a reasonable desktop screen story height. Right now the progress bar and sidebar differ in heights.

**Comment by jedtan** [comment]
> Nice work on this! Feedback:
> 
> * Does using the MUI drawer component cover what you need with animation? https://mui.com/material-ui/react-drawer/#main-content
> * Cut the "participants". Sorry, that was updated in the Figma [prototype page](https://www.figma.com/file/fKLCz2GfPG5f6HhEj9BlWD/Group-impact?node-id=152%3A10857&t=tkDjBerjKgcP7t9j-0) but not the prior static page.
> * Buttons:
>   
>   * Drawer close button feels a little asymmetric. Maybe it should be a circle here?
>   * "About the Cause" button definitely needs padding. I wonder if we overstepped on the button border-radius customization that forces 50% of height, because I think this kind of square-ish button breaks it. Thoughts?
> * Vertical sidebar:
>   
>   * The entire sidebar should have button behavior (`cursor: pointer`)
>   * See behavior in [prototype](https://www.figma.com/proto/fKLCz2GfPG5f6HhEj9BlWD/Group-impact?node-id=152%3A11013&scaling=min-zoom&page-id=152%3A10857&starting-point-node-id=152%3A11013)
>   * This might not be in scope of feedback you want now, but just flagging it.
> * Storybook/Chromatic:
>   
>   * Let's have a story of the open sidebar for UI testing
>   * Might be helpful in evaluating animation behavior to have sidebar/progress vertically fill the story height and set a reasonable desktop screen story height. Right now the progress bar and sidebar differ in heights.

Addressed the Buttons, and Participants. Will address the other animation feedback in the next PR. Also I think I'm missing where you're going with the Storybook/Chromatic comments. I think the default story of the sidebar is open, no?

Also, I think both the sidebar/progress fill the whole screen. I think they only differ in heights because of the margin on the top of the collapsed view, right?

**Comment by jedtan** [comment]
Oh I see what you're saying on the heights! I'll address that.

**Comment by kmjennison** [comment]
> I think the default story of the sidebar is open, no?

You're right, sorry! Maybe* what I meant to write was *closed* state: do we have a snapshot of the closed bar with the clickable flag? I see the vertical progress bar itself but not the complete UI for its use in the sidebar.

_\* Alternative possibility: I closed the sidebar in the Storybook review and then was like, it's closed! Time to comment something very helpful._ 😁

**Review by kmjennison — APPROVED** [review]
LGTM! ☕ Great work.

**Pull request merged**
