### PR TITLE
TFAC-935 Use Rounded, Teal Buttons

### PR DESCRIPTION
**Pull request by jedtan**

### CODE REVIEW

**Review by kmjennison — CHANGES_REQUESTED** [review]
This is looking pretty good! I think it'd be good to make some changes to improve consistency, avoid hindering future MUI use, and avoid a few undesired UI changes:
* Let's continue to use the default MUI button sizing
  * Rely on default theme sizing for small, medium, and large buttons
  * Specify border-radius as 1/2 height to maintain semicircle. Can probably just do 999px b/c browsers max out at 
semicircles.
  * Rationale: MUI has been thoughtful about spacing, so let's avoid awkward changes.
* The new color should take priority over cause theming
  * Let's use the teal color for buttons across all cause. The idea is a common color for call-to-actions.
  * This should be reflected in the Storybook notifications stories.
* Ensure the button `color` prop is still usable
  * Don't want to wreck customizability if a button needs to be a different color.
  * Haven't tested if this is a problem or not.
* Support outlined and text button variants with the same color
  * See demo: https://mui.com/material-ui/react-button/#outlined-button
  * To get nice color hexes, one approach is to set the teal color as a primary theme color and just inspect what MUI creates for the variants
  * **Possible easier approach:** set button default "color" prop to the teal color (see [overriding default props](https://mui.com/material-ui/customization/theme-components/#default-props)). Maybe MUI will handle all the color variations when done this way.
* Apply border-radius to other buttons, like the menu buttons (see screenshot below)
  * Probably applying this to the ButtonBase component will get the job done. However, we'll need to check for side-effects—e.g. we wouldn't want to change all the "switch cause" buttons into circles—but I think those have higher-priority styling to prevent that.
* Reduce visual importance of "Log Out" and "Switch to Classic" buttons
  * These were previously gray but are now very prominent (see screenshot below)
  * Maybe outlined button? Or a gray variant?

---
Example of improved menu button. I styled the bottom highlighted button in devtools.

Screen Shot 2022-11-16 at 11 54 38 AM

Let's decrease the prominence of this button and the "log out" button.

Screen Shot 2022-11-16 at 12 00 20 PM

**Comment by jedtan** [comment]
Thanks for the detailed feedback - I'll go through these and update the PR accordingly!

**Review by kmjennison — CHANGES_REQUESTED** [review]
Sorry if this wasn't clear: the active menu item should also have a rounded appearance. Currently, the active item is squared while the button appearance is rounded:

Screen Shot 2022-11-29 at 10 10 42 AM

**Comment by jedtan** [comment]
Huh, I thought I fixed this. Weird, sorry about the back and forth.

**Review by kmjennison — APPROVED** [review]
Looks awesome! Thanks for the iterations!

**Pull request merged**
